
AWS_ACCESS_KEY_ID_ENV_KEY = 'AKIAZ274RQKRARID3ZZB'
AWS_SECRET_ACCESS_KEY_ENV_KEY = "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"
MONGO_DB_URL_ENV_KEY = "mongodb+srv://Manu:OFbNVniqIU7LCmsb@cluster0.tskw9b1.mongodb.net/test"